module.exports = [{
  id: 1,
  category: "_",
  area_id: 1,
  rank: "S",
  name_ja: "吉田直樹",
  name_en: "Naoki Yoshida",
  scale: 10,
  name_fr: "Naoki Yoshida",
  name_de: "Naoki Yoshida"
}, {
  id: 2945,
  category: "v2",
  area_id: 30,
  rank: "A",
  scale: 1,
  interval: 210,
  name_ja: "醜男のヴォガージャ",
  name_en: "Vogaal Ja",
  name_fr: "Vogaal Ja",
  name_de: "Vogaal Ja"
}, {
  id: 2946,
  category: "v2",
  area_id: 31,
  rank: "A",
  scale: 1,
  interval: 225,
  name_ja: "ウンクテヒ",
  name_en: "Unktehi",
  name_fr: "Unktehi",
  name_de: "Unktehi"
}, {
  id: 2947,
  category: "v2",
  area_id: 32,
  rank: "A",
  scale: 1,
  interval: 210,
  name_ja: "魔導ヘルズクロー",
  name_en: "Hellsclaw",
  name_fr: "griffe des enfers magitek",
  name_de: "Höllenklaue"
}, {
  id: 2948,
  category: "v2",
  area_id: 33,
  rank: "A",
  scale: 1,
  interval: 210,
  name_ja: "ナン",
  name_en: "Nahn",
  name_fr: "Nahn",
  name_de: "Nahn"
}, {
  id: 2949,
  category: "v2",
  area_id: 34,
  rank: "A",
  scale: 1,
  interval: 240,
  name_ja: "マーベリー",
  name_en: "Marberry",
  name_fr: "marberry",
  name_de: "Marberry"
}, {
  id: 2950,
  category: "v2",
  area_id: 350,
  rank: "A",
  scale: 1,
  interval: 210,
  name_ja: "コンヌ",
  name_en: "Cornu",
  name_fr: "Cornu",
  name_de: "Cornu"
}, {
  id: 2936,
  category: "v2",
  area_id: 54,
  rank: "A",
  scale: 1,
  interval: 210,
  name_ja: "ファルネウス",
  name_en: "Forneus",
  name_fr: "Forneus",
  name_de: "Forneus"
}, {
  id: 2937,
  category: "v2",
  area_id: 55,
  rank: "A",
  scale: 1,
  interval: 180,
  name_ja: "メルティゼリー",
  name_en: "Melt",
  name_fr: "Fondu",
  name_de: "Schmelze"
}, {
  id: 2938,
  category: "v2",
  area_id: 56,
  rank: "A",
  scale: 1,
  interval: 225,
  name_ja: "ゲーデ",
  name_en: "Ghede Ti Malice",
  name_fr: "Guédé Ti-Malice",
  name_de: "Ghede Titus Häme"
}, {
  id: 2939,
  category: "v2",
  area_id: 57,
  rank: "A",
  scale: 1,
  interval: 240,
  name_ja: "ギルタブ",
  name_en: "Girtab",
  name_fr: "Girtab",
  name_de: "Girtab"
}, {
  id: 2940,
  category: "v2",
  area_id: 42,
  rank: "A",
  scale: 1,
  interval: 210,
  name_ja: "アレクトリオン",
  name_en: "Alectryon",
  name_fr: "Alectryon",
  name_de: "Alectryon"
}, {
  id: 2941,
  category: "v2",
  area_id: 43,
  rank: "A",
  scale: 1,
  interval: 240,
  name_ja: "サボテンダー・バイラリーナ",
  name_en: "Sabotender Bailarina",
  name_fr: "pampa ballerine",
  name_de: "Sabotender Bailarina"
}, {
  id: 2942,
  category: "v2",
  area_id: 44,
  rank: "A",
  scale: 1,
  interval: 180,
  name_ja: "マヘス",
  name_en: "Maahes",
  name_fr: "Maahes",
  name_de: "Mahisha"
}, {
  id: 2943,
  category: "v2",
  area_id: 45,
  rank: "A",
  scale: 1,
  interval: 225,
  name_ja: "ザニゴ",
  name_en: "Zanig'oh",
  name_fr: "Zanig'oh",
  name_de: "Zanig'oh"
}, {
  id: 2944,
  category: "v2",
  area_id: 46,
  rank: "A",
  scale: 1,
  interval: 240,
  name_ja: "ファイナルフレイム",
  name_en: "Dalvag's Final Flame",
  name_fr: "dernière flamme de Dalvag",
  name_de: "Letzt[a] Flamme[p] Dalvags"
}, {
  id: 2951,
  category: "v2",
  area_id: 63,
  rank: "A",
  scale: 1,
  interval: 180,
  name_ja: "マラク",
  name_en: "Marraco",
  name_fr: "Marraco",
  name_de: "Marraco"
}, {
  id: 2952,
  category: "v2",
  area_id: 67,
  rank: "A",
  scale: 1,
  interval: 210,
  name_ja: "クーレア",
  name_en: "Kurrea",
  name_fr: "Kurrea",
  name_de: "Kurrea"
}, {
  id: 2962,
  category: "v2",
  area_id: 30,
  rank: "S",
  scale: 10,
  interval: 3900,
  name_ja: "クロック・ミテーヌ",
  name_en: "Croque-mitaine",
  name_fr: "Croque-mitaine",
  name_de: "Croque Mitaine",
  condition_ja: "ラノシアソイルG3を採掘。 (ET19:00-22:00)",
  condition_en: "Mining Grade 3 La Noscean Topsoil. (ET19:00-22:00)",
  condition_fr: "Mining Grade 3 La Noscean Topsoil. (ET19:00-22:00)",
  condition_de: "Mining Grade 3 La Noscean Topsoil. (ET19:00-22:00)"
}, {
  id: 2963,
  category: "v2",
  area_id: 31,
  rank: "S",
  scale: 10,
  interval: 3e3,
  name_ja: "ケロゲロス",
  name_en: "Croakadile",
  name_fr: "Croabéros",
  name_de: "Quakquak",
  condition_ja: "満月になる夜のET17:00以降にスポーン候補座標を踏む。",
  condition_en: "ET17:00 of the night with a full moon.",
  condition_fr: "ET17:00 of the night with a full moon.",
  condition_de: "ET17:00 of the night with a full moon."
}, {
  id: 2964,
  category: "v2",
  area_id: 32,
  rank: "S",
  scale: 10,
  interval: 2520,
  name_ja: "ガーロック",
  name_en: "the Garlok",
  name_fr: "Garlok",
  name_de: "Garlok",
  condition_ja: "200分間(3時間20分間、[ET]約2日20時間34分)雨が降らない。",
  condition_en: "200 minutes (3 hours 20 minutes, [ET] about 2 days 20 hours 34 minutes) does not rain.",
  condition_fr: "200 minutes (3 hours 20 minutes, [ET] about 2 days 20 hours 34 minutes) does not rain.",
  condition_de: "200 minutes (3 hours 20 minutes, [ET] about 2 days 20 hours 34 minutes) does not rain."
}, {
  id: 2965,
  category: "v2",
  area_id: 33,
  rank: "S",
  scale: 10,
  interval: 3900,
  name_ja: "ボナコン",
  name_en: "Bonnacon",
  name_fr: "Bonnacon",
  name_de: "Bonnacon",
  condition_ja: "ラノシアリーキを草刈。 (ET8:00-11:00)",
  condition_en: "Harvesting La Noscean Leeks. (ET8:00-11:00)",
  condition_fr: "Harvesting La Noscean Leeks. (ET8:00-11:00)",
  condition_de: "Harvesting La Noscean Leeks. (ET8:00-11:00)"
}, {
  id: 2966,
  category: "v2",
  area_id: 34,
  rank: "S",
  scale: 10,
  interval: 2820,
  name_ja: "ナンディ",
  name_en: "Nandi",
  name_fr: "Nandi",
  name_de: "Nandi",
  condition_ja: "ミニオンを連れてスポーン候補地を踏む。ミニオンを出した状態からであれば騎乗してもよい。",
  condition_en: "Step over spawn point with minion. After call minion, you can call mount.",
  condition_fr: "Step over spawn point with minion. After call minion, you can call mount.",
  condition_de: "Step over spawn point with minion. After call minion, you can call mount."
}, {
  id: 2967,
  category: "v2",
  area_id: 350,
  rank: "S",
  scale: 10,
  interval: 3900,
  name_ja: "チェルノボーグ",
  name_en: "Chernobog",
  name_fr: "Czernobog",
  name_de: "Czernobog",
  condition_ja: "プレイヤーキャラクターが戦闘不能になる。",
  condition_en: "Death of players.",
  condition_fr: "Death of players.",
  condition_de: "Death of players."
}, {
  id: 2953,
  category: "v2",
  area_id: 54,
  rank: "S",
  scale: 10,
  interval: 2640,
  name_ja: "レドロネット",
  name_en: "Laideronnette",
  name_fr: "Laideronnette",
  name_de: "Laideronette",
  condition_ja: "30分間（[ET]約10時間17分）、雨が降り続く。",
  condition_en: "Raining for 30 minutes ([ET] about 10 hours 17 minutes)",
  condition_fr: "Raining for 30 minutes ([ET] about 10 hours 17 minutes)",
  condition_de: "Raining for 30 minutes ([ET] about 10 hours 17 minutes)"
}, {
  id: 2954,
  category: "v2",
  area_id: 55,
  rank: "S",
  scale: 10,
  interval: 4020,
  name_ja: "ウルガル",
  name_en: "Wulgaru",
  name_fr: "Wulgaru",
  name_de: "Wulgaru",
  condition_ja: "リーヴクエストを開始、またはクリア。",
  condition_en: "Levequest is initiated or completed.",
  condition_fr: "Levequest is initiated or completed.",
  condition_de: "Levequest is initiated or completed."
}, {
  id: 2955,
  category: "v2",
  area_id: 56,
  rank: "S",
  scale: 10,
  interval: 3e3,
  name_ja: "マインドフレア",
  name_en: "mindflayer",
  name_fr: "flagelleur mental",
  name_de: "Seelenbrenner",
  condition_ja: "新月の夜のET0:00以降にスポーン候補座標を踏む。",
  condition_en: "ET0:00 of the night of the new moon.",
  condition_fr: "ET0:00 of the night of the new moon.",
  condition_de: "ET0:00 of the night of the new moon."
}, {
  id: 2956,
  category: "v2",
  area_id: 57,
  rank: "S",
  scale: 10,
  interval: 3480,
  name_ja: "サウザンドキャスト・セダ",
  name_en: "Thousand-cast Theda",
  name_fr: "Theda la tripoteuse",
  name_de: "Tausendzahn Theda",
  condition_ja: "ジャッジ・レイを釣る。",
  condition_en: "Judgeray is caught by a Fisherman.",
  condition_fr: "Judgeray is caught by a Fisherman.",
  condition_de: "Judgeray is caught by a Fisherman."
}, {
  id: 2957,
  category: "v2",
  area_id: 42,
  rank: "S",
  scale: 10,
  interval: 3480,
  name_ja: "ゾーナ・シーカー",
  name_en: "Zona Seeker",
  name_fr: "Zona Seeker",
  name_de: "Zona Sucher",
  condition_ja: "銅鏡を釣る。",
  condition_en: "Glimmerscale is caught by a Fisherman.",
  condition_fr: "Glimmerscale is caught by a Fisherman.",
  condition_de: "Glimmerscale is caught by a Fisherman."
}, {
  id: 2958,
  category: "v2",
  area_id: 43,
  rank: "S",
  scale: 10,
  interval: 4080,
  name_ja: "ブロンテス",
  name_en: "Brontes",
  name_fr: "Brontes",
  name_de: "Brontes",
  condition_ja: "スポーン候補地点で食事をとる。",
  condition_en: "Consumption of any food at spawn point.",
  condition_fr: "Consumption of any food at spawn point.",
  condition_de: "Consumption of any food at spawn point."
}, {
  id: 2959,
  category: "v2",
  area_id: 44,
  rank: "S",
  scale: 10,
  interval: 4020,
  name_ja: "バルウール",
  name_en: "Lampalagua",
  name_fr: "Balaur",
  name_de: "Balaur",
  condition_ja: "リーヴクエストを開始、またはクリア。",
  condition_en: "Levequest is initiated or completed.",
  condition_fr: "Levequest is initiated or completed.",
  condition_de: "Levequest is initiated or completed."
}, {
  id: 2960,
  category: "v2",
  area_id: 45,
  rank: "S",
  scale: 10,
  interval: 2760,
  name_ja: "ヌニュヌウィ",
  name_en: "Nunyunuwi",
  name_fr: "Nunyunuwi",
  name_de: "Nunyunuwi",
  condition_ja: "南ザナラーンで発生するFATEを1時間失敗および時間切れさせない。ただし、NPCに話しかけることで開始するFATEは開始せずに無視してよい。（開始したら達成する必要あり。）",
  condition_en: "For a period of at least 60 minutes, no FATE in Southern Thanalan expires or fails.",
  condition_fr: "For a period of at least 60 minutes, no FATE in Southern Thanalan expires or fails.",
  condition_de: "For a period of at least 60 minutes, no FATE in Southern Thanalan expires or fails."
}, {
  id: 2961,
  category: "v2",
  area_id: 46,
  rank: "S",
  scale: 10,
  interval: 3480,
  name_ja: "ミニョーカオン",
  name_en: "Minhocao",
  name_fr: "Minhocao",
  name_de: "Minhocao",
  condition_ja: "アーススプライトを倒す。",
  condition_en: "Death of Earth Sprites.",
  condition_fr: "Death of Earth Sprites.",
  condition_de: "Death of Earth Sprites."
}, {
  id: 2968,
  category: "v2",
  area_id: 63,
  rank: "S",
  scale: 10,
  interval: 3600,
  name_ja: "サファト",
  name_en: "Safat",
  name_fr: "Safat",
  name_de: "Safat",
  condition_ja: "落下してHPが1になる。",
  condition_en: "Players falls to almost death (HP1).",
  condition_fr: "Players falls to almost death (HP1).",
  condition_de: "Players falls to almost death (HP1)."
}, {
  id: 2969,
  category: "v2",
  area_id: 67,
  rank: "S",
  scale: 10,
  interval: 3600,
  name_ja: "アグリッパ",
  name_en: "Agrippa the Mighty",
  name_fr: "Agrippa",
  name_de: "Agrippa",
  condition_ja: "トレジャーハントで宝箱を開ける。",
  condition_en: "Open treasure chests.",
  condition_fr: "Open treasure chests.",
  condition_de: "Open treasure chests."
}, {
  id: 887,
  category: "v2",
  area_id: 23,
  rank: "F",
  scale: 10,
  name_fr: "Défi: le Chevalier des ombres",
  name_en: "Steel Reign",
  name_ja: "古の闘神「オーディン」",
  name_de: "Der dunkle Reiter"
}, {
  id: 655,
  category: "v2",
  area_id: 63,
  rank: "F",
  scale: 10,
  name_fr: "Défi: l'ire du béhémoth",
  name_en: "Behold Now Behemoth",
  name_ja: "伝説の魔獣「ベヒーモス」",
  name_de: "Der legendäre Behemoth"
}, {
  id: 4362,
  category: "v3",
  area_id: 2200,
  rank: "A",
  name_ja: "ミルカ",
  name_en: "Mirka",
  name_fr: "Mirka",
  name_de: "Mirka",
  scale: 1,
  interval: 240
}, {
  id: 4363,
  category: "v3",
  area_id: 2200,
  rank: "A",
  name_ja: "リューバ",
  name_en: "Lyuba",
  name_fr: "Lyuba",
  name_de: "Lyuba",
  scale: 1,
  interval: 240
}, {
  id: 4370,
  category: "v3",
  area_id: 2100,
  rank: "A",
  name_ja: "エンケドラス",
  name_en: "Enkelados",
  name_fr: "Enkélados",
  name_de: "Engedoras",
  scale: 1,
  interval: 240
}, {
  id: 4371,
  category: "v3",
  area_id: 2100,
  rank: "A",
  name_ja: "シシウトゥル",
  name_en: "Sisiutl",
  name_fr: "Sisiutl",
  name_de: "Sisiutl",
  scale: 1,
  interval: 240
}, {
  id: 4368,
  category: "v3",
  area_id: 2002,
  rank: "A",
  name_ja: "ブネ",
  name_en: "Bune",
  name_fr: "Bune",
  name_de: "Bune",
  scale: 1,
  interval: 240
}, {
  id: 4369,
  category: "v3",
  area_id: 2002,
  rank: "A",
  name_ja: "アガトス",
  name_en: "Agathos",
  name_fr: "Agathos",
  name_de: "Agathos",
  scale: 1,
  interval: 240
}, {
  id: 4364,
  category: "v3",
  area_id: 2e3,
  rank: "A",
  name_ja: "パイルラスタ",
  name_en: "Pylraster",
  name_fr: "Pirlasta",
  name_de: "Xhauron",
  scale: 1,
  interval: 240
}, {
  id: 4365,
  category: "v3",
  area_id: 2e3,
  rank: "A",
  name_ja: "ワイバーンロード",
  name_en: "Lord of the Wyverns",
  name_fr: "seigneur des wyvernes",
  name_de: "Wyvern-Lord",
  scale: 1,
  interval: 240
}, {
  id: 4366,
  category: "v3",
  area_id: 2001,
  rank: "A",
  name_ja: "機兵のスリップキンクス",
  name_en: "Slipkinx Steeljoints",
  name_fr: "Slipkinx Joints-d'acier",
  name_de: "Rutschfix Stahlscharnier",
  scale: 1,
  interval: 240
}, {
  id: 4367,
  category: "v3",
  area_id: 2001,
  rank: "A",
  name_ja: "ストラス",
  name_en: "Stolas",
  name_fr: "Stolas",
  name_de: "Stolas",
  scale: 1,
  interval: 240
}, {
  id: 4372,
  category: "v3",
  area_id: 2101,
  rank: "A",
  name_ja: "キャムパクティ",
  name_en: "Campacti",
  name_fr: "Campacti",
  name_de: "Campacti",
  scale: 1,
  interval: 240
}, {
  id: 4373,
  category: "v3",
  area_id: 2101,
  rank: "A",
  name_ja: "センチブロッサム",
  name_en: "stench blossom",
  name_fr: "fleur nauséabonde",
  name_de: "Pestwurz",
  scale: 1,
  interval: 240
}, {
  id: 4374,
  category: "v3",
  area_id: 2200,
  rank: "S",
  name_ja: "カイザーベヒーモス",
  name_en: "kaiser behemoth",
  name_fr: "béhémoth empereur",
  name_de: "Kaiser-Behemoth",
  scale: 10,
  interval: 5040
}, {
  id: 4378,
  category: "v3",
  area_id: 2100,
  rank: "S",
  name_ja: "極楽鳥",
  name_en: "Bird of Paradise",
  name_fr: "oiseau de Paradis",
  name_de: "Paradiesvogel",
  scale: 10,
  interval: 5040
}, {
  id: 4377,
  category: "v3",
  area_id: 2002,
  rank: "S",
  name_ja: "ガンダルヴァ",
  name_en: "Gandarewa",
  name_fr: "Gandharva",
  name_de: "Gandalva",
  scale: 10,
  interval: 5040
}, {
  id: 4375,
  category: "v3",
  area_id: 2e3,
  rank: "S",
  name_ja: "セーンムルウ",
  name_en: "Senmurv",
  name_fr: "Sênmurw",
  name_de: "Simurgh",
  scale: 10,
  interval: 5040
}, {
  id: 4376,
  category: "v3",
  area_id: 2001,
  rank: "S",
  name_ja: "ペイルライダー",
  name_en: "the Pale Rider",
  name_fr: "Cavalier pale",
  name_de: "Bleich[a] Reiter",
  scale: 10,
  interval: 5040
}, {
  id: 4380,
  category: "v3",
  area_id: 2101,
  rank: "S",
  name_ja: "レウクロッタ",
  name_en: "Leucrotta",
  name_fr: "leucrotta",
  name_de: "Leucrotta",
  scale: 10,
  interval: 5040
}, {
  id: 3789,
  category: "v3",
  area_id: 2e3,
  rank: "F",
  scale: 10,
  name_fr: "Défi: coeurls brisés",
  name_en: "Coeurls Chase Boys Chase Coeurls",
  name_ja: "幻影の女王「クァールレギナ」",
  name_de: "Entmachtung der Königin"
}, {
  id: 3783,
  category: "v3",
  area_id: 2101,
  rank: "F",
  scale: 10,
  name_fr: "Proto-Ultima: la menace surgie du passé",
  name_en: "Prey Online",
  name_ja: "太古の脅威：ノクチルカ撃滅戦",
  name_de: "Ultima: Ein Prototyp tankt auf"
}, {
  id: 5990,
  category: "v4",
  area_id: 2406,
  rank: "A",
  name_ja: "オルクス",
  name_en: "Orcus",
  name_fr: "Orcus",
  name_de: "Orcus",
  scale: 1,
  interval: 240
}, {
  id: 5991,
  category: "v4",
  area_id: 2406,
  rank: "A",
  name_ja: "アール",
  name_en: "Erle",
  name_fr: "Erle",
  name_de: "Erle",
  scale: 1,
  interval: 240
}, {
  id: 5992,
  category: "v4",
  area_id: 2407,
  rank: "A",
  name_ja: "バックスタイン",
  name_en: "Vochstein",
  name_fr: "Vochstein",
  name_de: "Vochstein",
  scale: 1,
  interval: 240
}, {
  id: 5993,
  category: "v4",
  area_id: 2407,
  rank: "A",
  name_ja: "アクラブアメル",
  name_en: "Aqrabuamelu",
  name_fr: "Aqrabuamelu",
  name_de: "Aqrabuamelu",
  scale: 1,
  interval: 240
}, {
  id: 5994,
  category: "v4",
  area_id: 2408,
  rank: "A",
  name_ja: "マヒシャ",
  name_en: "Mahisha",
  name_fr: "Mahisha",
  name_de: "Mahisha",
  scale: 1,
  interval: 240
}, {
  id: 5995,
  category: "v4",
  area_id: 2408,
  rank: "A",
  name_ja: "ルミナーレ",
  name_en: "Luminare",
  name_fr: "Luminare",
  name_de: "Luminare",
  scale: 1,
  interval: 240
}, {
  id: 5996,
  category: "v4",
  area_id: 2409,
  rank: "A",
  name_ja: "船幽霊",
  name_en: "Funa Yurei",
  name_fr: "Funa Yurei",
  name_de: "Funa Yurei",
  scale: 1,
  interval: 240
}, {
  id: 5997,
  category: "v4",
  area_id: 2409,
  rank: "A",
  name_ja: "オニユメミ",
  name_en: "Oni Yumemi",
  name_fr: "Oni Yumemi",
  name_de: "Oni Yumemi",
  scale: 1,
  interval: 240
}, {
  id: 5998,
  category: "v4",
  area_id: 2410,
  rank: "A",
  name_ja: "ガジャースラ",
  name_en: "Gajasura",
  name_fr: "Gajasura",
  name_de: "Gajasura",
  scale: 1,
  interval: 240
}, {
  id: 5999,
  category: "v4",
  area_id: 2410,
  rank: "A",
  name_ja: "アンガダ",
  name_en: "Angada",
  name_fr: "Angada",
  name_de: "Angada",
  scale: 1,
  interval: 240
}, {
  id: 6e3,
  category: "v4",
  area_id: 2411,
  rank: "A",
  name_ja: "ギリメカラ",
  name_en: "Girimekhala",
  name_fr: "Girimekhala",
  name_de: "Girimekhala",
  scale: 1,
  interval: 240
}, {
  id: 6001,
  category: "v4",
  area_id: 2411,
  rank: "A",
  name_ja: "ソム",
  name_en: "Sum",
  name_fr: "Sum",
  name_de: "Sum",
  scale: 1,
  interval: 240
}, {
  id: 5987,
  category: "v4",
  area_id: 2406,
  rank: "S",
  name_ja: "ウドンゲ",
  name_en: "Udumbara",
  name_fr: "Udumbara",
  name_de: "Udumbara",
  scale: 10,
  interval: 5040
}, {
  id: 5988,
  category: "v4",
  area_id: 2407,
  rank: "S",
  name_ja: "ボーンクローラー",
  name_en: "Bone Crawler",
  name_fr: "Mangeur d'os",
  name_de: "Knochenkriecher",
  scale: 10,
  interval: 5040
}, {
  id: 5989,
  category: "v4",
  area_id: 2408,
  rank: "S",
  name_ja: "ソルト・アンド・ライト",
  name_en: "Salt and Light",
  name_fr: "Salaclux",
  name_de: "Salzlicht",
  scale: 10,
  interval: 5040
}, {
  id: 5984,
  category: "v4",
  area_id: 2409,
  rank: "S",
  name_ja: "オキナ",
  name_en: "Okina",
  name_fr: "Okina",
  name_de: "Okina",
  scale: 10,
  interval: 5040
}, {
  id: 5985,
  category: "v4",
  area_id: 2410,
  rank: "S",
  name_ja: "ガンマ",
  name_en: "Gamma",
  name_fr: "Gamma",
  name_de: "Gamma",
  scale: 10,
  interval: 5040
}, {
  id: 5986,
  category: "v4",
  area_id: 2411,
  rank: "S",
  name_ja: "オルガナ",
  name_en: "Orghana",
  name_fr: "Orghana",
  name_de: "Orghana",
  scale: 10,
  interval: 5040
}, {
  id: 6290,
  category: "v4",
  area_id: 2410,
  rank: "F",
  scale: 10,
  name_fr: "Défi: la renarde fait surface",
  name_en: "Foxy Lady",
  name_ja: "九尾の妖狐「玉藻御前」",
  name_de: "Fuchsige Dame"
}, {
  id: 6392,
  category: "v4",
  area_id: 2408,
  rank: "F",
  scale: 10,
  name_fr: "Défi: l'étalon survolté",
  name_en: "A Horse Outside",
  name_ja: "伝説の雷馬「イクシオン」",
  name_de: "Höllenross"
}, {
  id: 8906,
  category: "v5",
  area_id: 2953,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Nuckelavee",
  name_en: "Nuckelavee",
  name_ja: "ナックラヴィー",
  name_de: "Nuckelavee"
}, {
  id: 8907,
  category: "v5",
  area_id: 2953,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Nariphon",
  name_en: "Nariphon",
  name_ja: "ナリーポン",
  name_de: "Nariphon"
}, {
  id: 8911,
  category: "v5",
  area_id: 2954,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Traître",
  name_en: "Li'l Murderer",
  name_ja: "リルマーダー",
  name_de: "Klein[a] Mörder"
}, {
  id: 8912,
  category: "v5",
  area_id: 2954,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Huracan",
  name_en: "Huracan",
  name_ja: "フラカン",
  name_de: "Huracan"
}, {
  id: 8901,
  category: "v5",
  area_id: 2955,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Malikpampa",
  name_en: "Maliktender",
  name_ja: "マリクテンダー",
  name_de: "Malikkaktor"
}, {
  id: 8902,
  category: "v5",
  area_id: 2955,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Sugaar",
  name_en: "Sugaar",
  name_ja: "シュガール",
  name_de: "Sugaar"
}, {
  id: 8654,
  category: "v5",
  area_id: 2956,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "tas de boue",
  name_en: "the mudman",
  name_ja: "泥人",
  name_de: "Matschklops"
}, {
  id: 8655,
  category: "v5",
  area_id: 2956,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Pauldia",
  name_en: "O Poorest Pauldia",
  name_ja: "ポールディア",
  name_de: "gepeinigt[a] Pauldia"
}, {
  id: 8891,
  category: "v5",
  area_id: 2957,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Supay",
  name_en: "Supay",
  name_ja: "スペイ",
  name_de: "Supay"
}, {
  id: 8892,
  category: "v5",
  area_id: 2957,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Sasquatch arboricole",
  name_en: "Grassman",
  name_ja: "グラスマン",
  name_de: "Grasmann"
}, {
  id: 8896,
  category: "v5",
  area_id: 2958,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Roussalka",
  name_en: "Rusalka",
  name_ja: "ルサルカ",
  name_de: "Rusalka"
}, {
  id: 8897,
  category: "v5",
  area_id: 2958,
  rank: "A",
  scale: 1,
  interval: 240,
  name_fr: "Baal",
  name_en: "Baal",
  name_ja: "バール",
  name_de: "Baal"
}, {
  id: 8653,
  category: "v5",
  area_id: 2956,
  rank: "S",
  scale: 10,
  interval: 5040,
  name_fr: "Aglaope",
  name_en: "Aglaope",
  name_ja: "アグラオペ",
  name_de: "Aglaope"
}, {
  id: 8890,
  category: "v5",
  area_id: 2957,
  rank: "S",
  scale: 10,
  interval: 5040,
  name_fr: "Ixtab",
  name_en: "Ixtab",
  name_ja: "イシュタム",
  name_de: "Ixtab"
}, {
  id: 8895,
  category: "v5",
  area_id: 2958,
  rank: "S",
  scale: 10,
  interval: 5040,
  name_fr: "Gunitt",
  name_en: "Gunitt",
  name_ja: "グニット",
  name_de: "Gunitt"
}, {
  id: 8915,
  category: "v5",
  area_id: 2949,
  rank: "S",
  scale: 10,
  interval: 5040,
  name_fr: "rébellion pardonnée",
  name_en: "forgiven rebellion",
  name_ja: "フォーギヴン・リベリオン",
  name_de: "geläutert[a] Rebellion"
}, {
  id: 8822,
  category: "v5",
  area_id: 2954,
  rank: "F",
  scale: 10,
  name_fr: "Formidable: l'arme secrète",
  name_en: "A Finale Most Formidable",
  name_ja: "激闘フォーミダブル：切り札起動",
  name_de: "Ein formidabler Kampf: Der Gigant"
}, {
  id: 8234,
  category: "v5",
  area_id: 2958,
  rank: "F",
  scale: 10,
  name_fr: "L'annonciatrice du chaos: bataille au sommet des fonds",
  name_en: "The Head, the Tail, the Whole Damned Thing",
  name_ja: "厄災のアルケオタニア：深海の討伐戦",
  name_de: "Schrecken der Tiefsee Archaeotania: Die Bestie"
}]